version: '3.4'
services:
  sonar-postgres:
    image: postgres
    container_name: sonar-postgres
    environment: 
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - "5432:5432"
    networks:
      - sonarqubenet
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarqubenet    
    environment: 
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonar-postgres:5432/sonar
    depends_on:
      - sonar-postgres
networks:
  sonarqubenet:
    driver: bridge
